# Generated by Django 5.0.4 on 2025-03-19 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_enhance_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='image_path',
        ),
        migrations.AddField(
            model_name='donation',
            name='image',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='image_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='image_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
